name: Prisma Deploy

on:
  push:
    branches:
      - main   # only run when deploying to main

jobs:
  migrate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Generate Prisma Client
        run: npx prisma generate

      - name: Push schema to DB
        run: npx prisma db push
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

      - name: Seed DB
        run: npx tsx prisma/seed.ts
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
